[package]
name = "icrc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib"]

[dependencies]
async-trait = "0.1.68"
candid = "0.8.4"
ic-cdk = "0.9.2"
serde = "1.0.164"